"""
Pydantic models for LLM operations
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field



class LLMResponse(BaseModel):
    """Response model from LLM operations"""
    text: str = Field(..., description="Text generated by the LLM")
    model_id: str = Field(..., description="Model used for generation")
    usage: Dict[str, Any] = Field(default_factory=dict, description="Usage information")
    
    
class ChatMessage(BaseModel):
    """Individual message in a conversation"""
    role: str = Field(..., description="Role of the message: user, assistant, system")
    content: str = Field(..., description="Content of the message")


class LLMRequest(BaseModel):
    """Request model for LLM operations"""
    prompt: str = Field(..., description="Prompt for the LLM")
    max_tokens: Optional[int] = Field(1000, description="Maximum number of tokens to generate")
    temperature: Optional[float] = Field(0.7, description="Temperature for generation randomness")
    model_id: Optional[str] = Field(None, description="ID of the model to use")
    session_id: Optional[str] = Field(None, description="Conversation session id to store history")
    top_k: Optional[int] = Field(None, description="Número de citas/resultados a recuperar (opcional)")


class ChatRequest(BaseModel):
    """Request model for conversational chat"""
    message: ChatMessage = Field(..., description="Response message from the assistant")
    max_tokens: Optional[int] = Field(1000, description="Maximum number of tokens to generate")
    temperature: Optional[float] = Field(0.7, description="Temperature for generation randomness")
    model_id: Optional[str] = Field(None, description="ID of the model to use")
    session_id: Optional[str] = Field(None, description="Conversation session id to store history")
    top_k: Optional[int] = Field(None, description="Número de citas/resultados a recuperar (opcional)")


class ChatResponse(BaseModel):
    """Response model from chat operations"""
    message: ChatMessage = Field(..., description="Response message from the assistant")
    model_id: str = Field(..., description="Model used for generation")
    usage: Dict[str, Any] = Field(default_factory=dict, description="Usage information")
    request_feedback: Optional[bool] = Field(False, description="Whether to request user feedback")  
    
    
    
# class ChatRequest(BaseModel):
#     """Request model for conversational chat"""
#     messages: List[ChatMessage] = Field(..., description="List of conversation messages")
#     max_tokens: Optional[int] = Field(1000, description="Maximum number of tokens to generate")
#     temperature: Optional[float] = Field(0.7, description="Temperature for generation randomness")
#     model_id: Optional[str] = Field(None, description="ID of the model to use")
